---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ztw.
--- DateTime: 3/23/2024 3:25 PM
---
---比较线程标识与锁中的标识是否一致
if (redis.call('get',keys[1]) == ARGV[1]) then
    ---释放锁
    return redis.call('del',keys[1])
end
return 0